---

- name: install project
  import_role: 
    name: openshift_project
  vars:
    ocp_project: "{{ app_name }}-{{ ocp_user }}"
    ocp_project_display_name: "{{ app_name }}-{{ ocp_user }}"
    ocp_project_desc: "{{ app_name }}-{{ ocp_user }}"

- name: install openshift_rdbms
  import_role: 
    name: openshift_rdbms
  vars:
    rdbms_app_name: "{{ ocp_user }}-{{ rdbms_app_name_base }}"
    resources_dir: "{{ resources_base_dir }}/openshift_rdbms"
  when: install_rdbms|bool

- name: install optaweb-employee-rostering
  import_role: 
    name: optaweb-employee-rostering
  vars:
    service_name: "{{ ocp_user }}-postgresql"
    resources_dir: "{{ resources_base_dir }}/optaweb-employee-rostering"
  when: install_optaweb_employee_rostering|bool

- name: install patient-service
  import_role: 
    name: patient-service
  vars:
    service_name: "{{ ocp_user }}-patient-service"
    resources_dir: "{{ resources_base_dir }}/patient-service"
  when: install_patient_service|bool
